server:
  port: 8001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: kertaskerja-bontang
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://192.168.194.241:5432/kertaskerja_bontang
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

kertaskerja:
  status: Kertas Kerja UP!
  security:
    setup-enabled: ${KERTASKERJA_SETUP_ENABLED:true}
    jwt:
      secret: vuebu3LXBxgdvMsoKwHaD5WvPjijTVT8yd8UduKN2Yg=
      ttl: ${KERTASKERJA_JWT_TTL:8h}

management:
  endpoints:
    web:
      exposure:
        include: mappings
